config/routes.rb
Rails.application.routes.draw do
  resources :puntos

  devise_for :users
  root"pages#home"
  get "about" => "pages#about"

  

end

app/models/punto.rb
class Punto < ActiveRecord::Base
<<<<<<< HEAD
=======

>>>>>>> a51d7bb18aa0280f8a309304c5457fb394998044
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

<<<<<<< HEAD

   has_many :puntos
=======
  has_many :puntos
>>>>>>> a51d7bb18aa0280f8a309304c5457fb394998044
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  	def home
  	end

  	def about 
	end 
end

app/controllers/puntos_controller.rb
class PuntosController < ApplicationController
  before_action :set_punto, only: [:show, :edit, :update, :destroy]
<<<<<<< HEAD
  before_action :authenticate_user!

=======
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
>>>>>>> a51d7bb18aa0280f8a309304c5457fb394998044
  # GET /puntos
  # GET /puntos.json
  def index
    @puntos = Punto.all
  end

  # GET /puntos/1
  # GET /puntos/1.json
  def show
    @punto = current_user.puntos.build
    
  end

  # GET /puntos/new
  def new
    @punto = current_user.puntos.build
  end

  # GET /puntos/1/edit
  def edit
  end

  # POST /puntos
  # POST /puntos.json
  def create
    @punto = current_user.puntos.build(punto_params)

    if @punto.update(punto_params)
      redirect_to @punto, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end

      
  end

  # PATCH/PUT /puntos/1
  # PATCH/PUT /puntos/1.json
  def update
    respond_to do |format|
      if @punto.update(punto_params)
        format.html { redirect_to @punto, notice: 'Punto was successfully updated.' }
        format.json { render :show, status: :ok, location: @punto }
      else
        format.html { render :edit }
        format.json { render json: @punto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puntos/1
  # DELETE /puntos/1.json
  def destroy
    @punto.destroy
    respond_to do |format|
      format.html { redirect_to puntos_url, notice: 'Punto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_punto
      @punto = Punto.find(params[:id])
    end

    def correct_user
      @punto = current_user.puntos.find_by(id: params[:id])
      redirect_to puntos_path, notice: "No estás autorizado para ver este contenido" if @punto.nil?
    end 



    # Never trust parameters from the scary internet, only allow the white list through.
    def punto_params
      params.require(:punto).permit(:origen, :destino, :destinodos, :hora, :valor, :notas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/puntos_helper.rb
module PuntosHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "LuloYeye", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>

        <% end %> 
    </ul>
  </div><!-- /.navbar-collapse -->
 </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lulos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
<%= render 'layouts/header' %>

<div class="container">
          <%= yield %>
     </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About US</h1>
<p>We are working on our One Month Rails Pinteresting app</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>La mejor manera de hacer tus vueltas en bogotá</h1>
     <% if user_signed_in? %>
          Hola, qué gusto tenerte otra vez por acá :)
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/puntos/_form.html.erb
<%= form_for(@punto) do |f| %>
  <% if @punto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@punto.errors.count, "error") %> prohibited this punto from being saved:</h2>

      <ul>
      <% @punto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :origen %><br>
    <%= f.text_field :origen, class: "form-group" %>
  </div>
  <div class="form-group">
    <%= f.label :destino %><br>
    <%= f.text_field :destino, class: "form-group" %>
  </div>
  <div class="form-group">
    <%= f.label :destino_Extra_Opcional %><br>
    <%= f.text_field :destinodos, class: "form-group" %>
  </div>
  <div class="form-group">
    <%= f.label :hora_de_recogida %><br>
    <%= f.datetime_select :hora, class: "form-group" %>
  </div>
  <div class="form-group">
    <%= f.label :valor %><br>
    <%= f.number_field :valor, class: "form-group" %>
  </div>
  <div class="form-group">
    <%= f.label :notas_e_instrucciones %><br>
    <%= f.text_field :notas, class: "form-group" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary", value: "Nueva vuelta"  %>
  </div>
<% end %>

app/views/puntos/edit.html.erb
<h1>Editing punto</h1>

<%= render 'form' %>

<%= link_to 'Show', @punto %> |
<%= link_to 'Back', puntos_path %>

app/views/puntos/index.html.erb
<h1>listado de Vueltras</h1>

<table>
  <thead>
    <tr>
      <th>Origen</th>
      <th>Destino</th>
      <th>Destino Extra (opcional)</th>
      <th>Usuario</th>
      <th>Hora de recogida</th>
      <th>Valor Mercancía</th>
      <th>Notas e instrucciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puntos.each do |punto| %>
      <tr>
        <td><%= punto.origen %></td>
        <td><%= punto.destino %></td>
        <td><%= punto.destinodos %></td>
        <td><%= punto.user.email if punto.user %></td>
        <td><%= punto.hora %></td>
        <td><%= punto.valor %></td>
        <td><%= punto.notas %></td>
        <td><%= link_to 'Ver', punto %></td>
      <% if punto.user == current_user %>
        <td><%= link_to 'Editar', edit_punto_path(punto) %></td>
        <td><%= link_to 'Eliminar', punto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'Nueva vuelta', new_punto_path %>
<% end %>

app/views/puntos/new.html.erb
<h1>Nueva Vuelta</h1>

<%= render 'form' %>

<%= link_to 'atrás', puntos_path %>

app/views/puntos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origen:</strong>
  <%= @punto.origen %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @punto.destino %>
</p>

<p>
  <strong>Destino Extra(opcional):</strong>
  <%= @punto.destinodos %>
</p>

<p>
  <strong>Hora de recogida:</strong>
  <%= @punto.hora %>
</p>

<p>
  <strong>Valor Mercancía:</strong>
  <%= @punto.valor %>
</p>

<p>
  <strong>Notas e instrucciones:</strong>
  <%= @punto.notas %>
</p>


<%= link_to 'Edit', edit_punto_path(@punto) %> 

<%= link_to 'Back', puntos_path %>